/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rental_System;

import java.awt.CardLayout;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Simmigon Flagg
 */
public class AppHome extends javax.swing.JFrame {

    /**
     * Creates new form LoginView
     */
    Database connection = new Database();
    //LoginController user = new LoginController();
    CardLayout showCardView = null;
    
    private String CredentialsLevel = "";
    
    public AppHome() {
        initComponents();
        // Set when login
        Credentials(CredentialsLevel);
        String ccurrentTime;
        // Date date;
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    
                    String[] time;
                    Date date = new Date();
                    labelTime.setText(date.toString());
                    
                }
                
            }
        }.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelButton = new javax.swing.JPanel();
        btnTenants = new javax.swing.JButton();
        btnApplicants = new javax.swing.JButton();
        btnAdmins = new javax.swing.JButton();
        btnEmployees = new javax.swing.JButton();
        btnMaintenance = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblLoginName = new javax.swing.JLabel();
        labelTime = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        PanelCard = new javax.swing.JPanel();
        cardPanels = new javax.swing.JPanel();
        login = new javax.swing.JPanel();
        txtLoginName = new javax.swing.JTextField();
        txtPasswordLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        adminView1 = new Rental_System.AdminView();
        tenantsView1 = new Rental_System.TenantsView();
        maintenanceView1 = new Rental_System.MaintenanceView();
        applicantsView1 = new Rental_System.ApplicantsView();
        clientView1 = new Rental_System.ClientView();
        reportsView1 = new Rental_System.ReportsView();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(958, 538));
        setName("Application"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelButton.setBackground(new java.awt.Color(255, 255, 153));
        panelButton.setOpaque(false);

        btnTenants.setText("Tenants");
        btnTenants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenantsActionPerformed(evt);
            }
        });

        btnApplicants.setText("Applicants");
        btnApplicants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplicantsActionPerformed(evt);
            }
        });

        btnAdmins.setText("Admin");
        btnAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminsActionPerformed(evt);
            }
        });

        btnEmployees.setText("Employee");
        btnEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeesActionPerformed(evt);
            }
        });

        btnMaintenance.setText("Maintenance");
        btnMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceActionPerformed(evt);
            }
        });

        btnReports.setText("Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTenants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnApplicants)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaintenance, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAdmins, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEmployees)
                .addContainerGap())
        );

        panelButtonLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdmins, btnApplicants, btnEmployees, btnTenants});

        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTenants)
                    .addComponent(btnApplicants)
                    .addComponent(btnEmployees)
                    .addComponent(btnMaintenance)
                    .addComponent(btnAdmins)
                    .addComponent(btnReports))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        panelButtonLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAdmins, btnApplicants, btnEmployees, btnMaintenance, btnTenants});

        getContentPane().add(panelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 935, -1));

        jPanel1.setPreferredSize(new java.awt.Dimension(958, 48));

        lblLoginName.setText("Welcome, ");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 478, Short.MAX_VALUE)
                .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblLoginName)
                        .addComponent(labelTime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelCard.setBackground(new java.awt.Color(255, 153, 153));
        PanelCard.setOpaque(false);
        PanelCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cardPanels.setBackground(new java.awt.Color(0, 0, 153));
        cardPanels.setMaximumSize(new java.awt.Dimension(0, 0));
        cardPanels.setPreferredSize(new java.awt.Dimension(700, 300));
        cardPanels.setLayout(new java.awt.CardLayout());

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginLayout = new javax.swing.GroupLayout(login);
        login.setLayout(loginLayout);
        loginLayout.setHorizontalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPasswordLogin)
                    .addComponent(txtLoginName, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(479, 479, 479))
        );
        loginLayout.setVerticalGroup(
            loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(txtLoginName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPasswordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnLogin)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        cardPanels.add(login, "Login View");
        cardPanels.add(adminView1, "Admins");
        cardPanels.add(tenantsView1, "Tenants");
        cardPanels.add(maintenanceView1, "Maintenance");
        cardPanels.add(applicantsView1, "Applicants");
        cardPanels.add(clientView1, "Clients");
        cardPanels.add(reportsView1, "Reports");

        PanelCard.add(cardPanels, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 720, 310));

        getContentPane().add(PanelCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, 935, 330));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Rental_System/LoginBackground.JPG"))); // NOI18N
        Background.setPreferredSize(new java.awt.Dimension(955, 537));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnApplicantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplicantsActionPerformed
        // TODO add your handling code here:
        showCardView.show(cardPanels, "Applicants");
    }//GEN-LAST:event_btnApplicantsActionPerformed

    private void btnMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceActionPerformed
        // TODO add your handling code here:
        showCardView.show(cardPanels, "Maintenance");
    }//GEN-LAST:event_btnMaintenanceActionPerformed

    private void btnTenantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenantsActionPerformed
        
        showCardView.show(cardPanels, "Tenants");

    }//GEN-LAST:event_btnTenantsActionPerformed

    private void btnAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminsActionPerformed
        showCardView.show(cardPanels, "Admins");
    }//GEN-LAST:event_btnAdminsActionPerformed

    private void btnEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeesActionPerformed
        
        showCardView.show(cardPanels, "Clients");
    }//GEN-LAST:event_btnEmployeesActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        showCardView.show(cardPanels, "Reports");
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        txtLoginName.setText(null);
        txtPasswordLogin.setText(null);
        btnLogin.setVisible(true);
        
        showCardView.show(cardPanels, "Login View");
        // showCardView = (CardLayout) login.getLayout();

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        char[] p = txtPasswordLogin.getPassword();
        String pass = new String();
        for (int i = 0; i < p.length; i++) {
            char q = p[i];
            pass += q;
        }
        
        Object[] logins = connection.isLogin(txtLoginName.getText(), pass);
        connection.closeDatabase();
        
        System.out.println("Login Name:" + txtLoginName.getText());
        System.out.println("Login pass:" + pass);
        
        for (Object login1 : logins) {
            System.out.println("login stuff: " + login1);
        }
        
        if ((boolean) logins[0] && (int) logins[3] == 1) {
            Credentials("Admins");
            showCardView.show(cardPanels, "Admins");
            lblLoginName.setText("Admin : " + logins[1]);//get user Name if admin;
        } else if ((boolean) logins[0] && (int) logins[4] == 1) {
            Credentials("Client");
            showCardView.show(cardPanels, "Applicants");
            lblLoginName.setText("Employee : " + logins[1]);//get user Name if admin;
        } else {
            JOptionPane.showMessageDialog(panelButton, "Invalid password");
            
        }
        txtLoginName.setText(null);
        txtPasswordLogin.setText(null);
    }//GEN-LAST:event_btnLoginActionPerformed
    public void Credentials(String CredentialsLevel) {
        
        String name = new String();
        
        switch (CredentialsLevel) {
            case "Admins":
                // lblLoginName.setText(name + "Admin");//get user Name if admin;
                showCardView.show(cardPanels, "Admins");
                //  showCardView.show(cardPanels, CredentialsLevel);

                btnAdmins.setVisible(true);
                btnApplicants.setVisible(true);
                btnEmployees.setVisible(true);
                btnMaintenance.setVisible(true);
                btnTenants.setVisible(true);
                btnReports.setVisible(true);
                
                btnLogin.setVisible(false);
                // btnLoginCancel.setVisible(false);
                break;
            case "Client":
                
                lblLoginName.setText(name + "");//
                showCardView.show(cardPanels, "Applicants");
                //    showCardView.show(cardPanels, CredentialsLevel);

                btnMaintenance.setVisible(true);
                btnTenants.setVisible(true);
                btnApplicants.setVisible(true);
                btnReports.setVisible(true);
                
                btnAdmins.setVisible(false);
                btnEmployees.setVisible(false);
                btnLogin.setVisible(false);
                //  btnLoginCancel.setVisible(false);

                break;
            case "Login View":
                
                showCardView.show(cardPanels, "Login View");

                lblLoginName.setText("");
                //    showCardView = (CardLayout) cardPanels.getLayout();
                btnApplicants.setVisible(false);
                btnMaintenance.setVisible(false);
                btnTenants.setVisible(false);
                btnAdmins.setVisible(false);
                btnEmployees.setVisible(false);
                btnReports.setVisible(false);
                
                break;
            
            default:
                
                lblLoginName.setText("");
                showCardView = (CardLayout) cardPanels.getLayout();
                btnApplicants.setVisible(false);
                btnMaintenance.setVisible(false);
                btnTenants.setVisible(false);
                btnAdmins.setVisible(false);
                btnEmployees.setVisible(false);
                btnReports.setVisible(false);
                break;
        }
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JPanel PanelCard;
    private Rental_System.AdminView adminView1;
    private Rental_System.ApplicantsView applicantsView1;
    private javax.swing.JButton btnAdmins;
    private javax.swing.JButton btnApplicants;
    private javax.swing.JButton btnEmployees;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMaintenance;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnTenants;
    public javax.swing.JPanel cardPanels;
    private Rental_System.ClientView clientView1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTime;
    public javax.swing.JLabel lblLoginName;
    private javax.swing.JPanel login;
    private Rental_System.MaintenanceView maintenanceView1;
    public javax.swing.JPanel panelButton;
    private Rental_System.ReportsView reportsView1;
    private Rental_System.TenantsView tenantsView1;
    private javax.swing.JTextField txtLoginName;
    public javax.swing.JPasswordField txtPasswordLogin;
    // End of variables declaration//GEN-END:variables
}
